version: '3'
services:
  node:
    image: kjunha77/lxp-node
    tty: true
    networks:
        lxpnet:
            ipv4_address: 172.19.0.10 
    ports:
      - "8545:8545"
      - "30303:30303"
    container_name: node
    working_dir: /usr/app
  server:
    build: .
    tty: true
    networks:
        lxpnet:
            ipv4_address: 172.19.0.3
    ports:
      - "8080:8080"
    container_name: server
    working_dir: /usr/src/app
  monitor:
    build: ./monitor
    tty: true
    networks:
        lxpnet:
            ipv4_address: 172.19.0.5
    ports:
      - "3000:3000"
      - "3001:3001"
    container_name: monitor
    working_dir: /usr/src/app
networks: 
    lxpnet:
        driver: bridge
        ipam:
            config:
                - subnet:  172.19.0.0/24
                
                
